name: Build Bruce S3

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Patch libnet80211 (для сниффинга)
        run: |
          pio pkg install -p espressif32 -t toolchain-xtensa-esp32s3
          f="$HOME/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/lib/libnet80211.a"
          t="$HOME/.platformio/packages/toolchain-xtensa-esp32s3/xtensa-esp32s3-elf/bin/objcopy"
          if [[ -f "$f" ]]; then
            $t --weaken-symbol=ieee80211_raw_frame_sanity_check "$f" "${f}.temp"
            mv "$f" "${f}.old"
            mv "${f}.temp" "$f"
          fi

      - name: Build
        run: pio run -e esp32-s3-devkitc-1-psram

      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
          name: bruce-bin
          path: .pio/build/esp32-s3-devkitc-1-psram/firmware.bin
